import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import Providers from "@/app/providers";
import {Toaster} from "@/components/ui/sonner";
import {AppSidebar} from "@/components/sidebar";
import {SidebarInset, SidebarProvider, SidebarTrigger} from "@/components/ui/sidebar";

import {GoogleTagManager,GoogleAnalytics} from '@next/third-parties/google'

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
                                             children,
                                         }: Readonly<{
    children: React.ReactNode;
}>) {
    // const cookieStore = await cookies();
    // const defaultOpen = cookieStore.get("sidebar_state")?.value === "true"
    // const sessData = await auth.api.getSession({
    //   headers: await headers(),
    // });

    // @ts-ignore
    return (
        <html lang="en" suppressHydrationWarning>
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        {/*// <!-- Google tag (gtag.js) -->*/}
        <GoogleTagManager gtmId={process.env.NEXT_PUBLIC_GTM_ID ?? ""}/>
        <GoogleAnalytics gaId={process.env.NEXT_PUBLIC_GTM_ID ?? ""}/>


        <Toaster richColors/>
        <Providers>
            <SidebarProvider defaultOpen={true}>
                <AppSidebar/>
                <SidebarInset>

                    <main className={"grow"}>
                        <SidebarTrigger/>
                        {children}
                    </main>
                </SidebarInset>

            </SidebarProvider>
        </Providers>
        </body>
        </html>
    );
}
